import {
  Award,
  Bookmark,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  CircleCheck,
  Code,
  Database,
  Dribbble,
  Facebook,
  FileText,
  FlaskConical,
  Github,
  GraduationCap,
  Heart,
  Instagram,
  Languages,
  Lightbulb,
  Link as LinkIcon,
  Linkedin,
  Mail,
  MapPin,
  Microscope,
  Phone,
  Presentation,
  Rocket,
  Shield,
  Sparkles,
  Star,
  Stethoscope,
  Trophy,
  Twitter,
  Users,
  Wrench,
  Youtube,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  award: Award,
  bookmark: Bookmark,
  "book-open": BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  building: Building2,
  "circle-check": CircleCheck,
  code: Code,
  database: Database,
  dribbble: Dribbble,
  facebook: Facebook,
  "file-text": FileText,
  "flask-conical": FlaskConical,
  github: Github,
  "graduation-cap": GraduationCap,
  heart: Heart,
  instagram: Instagram,
  languages: Languages,
  lightbulb: Lightbulb,
  link: LinkIcon,
  linkedin: Linkedin,
  mail: Mail,
  "map-pin": MapPin,
  microscope: Microscope,
  phone: Phone,
  presentation: Presentation,
  rocket: Rocket,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  trophy: Trophy,
  twitter: Twitter,
  x: Twitter,
  users: Users,
  wrench: Wrench,
  youtube: Youtube,
};

export const ICON_NAMES = Object.keys(ICONS);

export function DynamicIcon({
  name,
  className,
  "aria-hidden": ariaHidden = true,
}: {
  name: string | null | undefined;
  className?: string;
  "aria-hidden"?: boolean;
}) {
  const Icon = ICONS[(name ?? "").toLowerCase()] ?? Sparkles;
  return <Icon className={className} aria-hidden={ariaHidden} />;
}
